services:
  app:
    image: golang:1.22-alpine
    container_name: ecommerce_app
    working_dir: /app
    command: sh -c "go run ./cmd/main.go"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "ecommerce.local:host-gateway"

  db:
    image: postgres:16
    container_name: ecommerce_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
